services:
  backend:
    build:
      context: ./backend
    ports:
      - "8082:8082"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
