spring.application.name=organia_fullstack_task
server.port=${PORT:8082}

spring.datasource.url=jdbc:${DB_CONNECTION:mysql}://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_DATABASE:task_management}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:change-this-secret-key-to-a-long-random-production-value}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
